// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAngleChange();
void onButtonChange();

int angle;
bool button;

void initProperties(){

  ArduinoCloud.addProperty(angle, READWRITE, ON_CHANGE, onAngleChange, 360);
  ArduinoCloud.addProperty(button, READWRITE, ON_CHANGE, onButtonChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
